# Generated by Django 5.2.3 on 2025-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='creator_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='date_range',
            field=models.CharField(default='June 2025', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('fa-code', 'Code'), ('fa-database', 'Database'), ('fa-gamepad', 'Gamepad'), ('fa-paint-brush', 'Design'), ('fa-robot', 'AI/Robot'), ('fa-lock', 'Cybersecurity'), ('fa-mobile-alt', 'Mobile'), ('fa-globe', 'Web')], default='fa-code', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.CharField(default='Django, Bootstrap', max_length=200),
        ),
    ]
