# Generated by Django 5.2.3 on 2025-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_image_project_creator_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-code', 'Code'), ('fa-database', 'Database'), ('fa-gamepad', 'Gamepad'), ('fa-paint-brush', 'Design'), ('fa-robot', 'AI/Robot'), ('fa-lock', 'Cybersecurity'), ('fa-mobile-alt', 'Mobile'), ('fa-globe', 'Web')], default='fa-code', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
